# Servlet

NOTE: 시작하기 앞서, 기본 설정

* java version: *21*
* Dependencies: *Spring Web* , *Lombok*

NOTE: 프로젝트 테스트

* ServletApplication.main() 메서드 실행 후 로그 확인
** tomcat -> portnum 8080 으로 잘 띄워져 있는지

### Tomcat Server

* 기존 웹 애플리케이션 서버 띄우는 법
** 기존방식
*** 서버를 설치 후 클래스 파일을 빌드해서 올림

** 스프링부트 방식
*** 스프링 부트를 통해서 문제 해결
*** 스프링 부트는 톰캣 서버를 내장하고 있기에 별도의 설치 없이 사용 가능
*** 서버를 직접 띄우고, 클래스파일을 올릴 필요가 없어짐

### 서블릿 띄우기
[source,java]
----
@ServletComponentScan
@SpringBootApplication
public class ServletApplication {

	public static void main(String[] args) {
		SpringApplication.run(ServletApplication.class, args);
	}
}
----
* 위의 코드에서 ServletComponentScan이 없으면, Servlet으로 등록된 소스코드를 읽어들이지 않음. 필수적으로 들어가야 함


### 서블릿 등록 방법
[source,java]
----
@WebServlet(name = "exampleServlet", urlPatterns = "/example")
public class ExampleServlet extends HttpServlet {
    @Override
    protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    }
}
----

* 서블릿을 등록하는 기본적인 방법으로, Spring에 의존하지 않은 순수 자바에 의존하는 방법이다.
** *WebServlet*: 서블릿 애노테이션
** *name*: 서블릿 이름
** *urlPatterns*: URL 매핑

-> 요청시 http:localhost:8080/urlPatterns 로 요청하면 된다.

[source]
----
request = org.apache.catalina.connector.RequestFacade@7b656089
response = org.apache.catalina.connector.ResponseFacade@3eb3d2b
----

-> 서블릿은 요청과 응답 객체를 만들어 전달받는다. 이 또한 spring에 의존한 객체가 아니다.

----
지금까지의 코드는 spring에 의존한 객체나 메서드등 아무것도 없다. 단지 톰캣 아파치 서버를 띄우기 위한 용도로써만 사용했다
----

### 서블릿 컨테이너 동작방식

1. 웹 브라우저 요청
2. WAS 에서 Request, Response 객체 생성
3. 서블릿 컨테이너에서 요청에 대한 처리
4. WAS로 응답 메세지 생성
5. 웹 브라우저에 전달

### HttpServletRequest

* HttpServletRequest 역할
** HTTP 요청 메세지를 편리하게 사용할 수 있도록 HTTP 요청 메세지를 파싱
** HttpServletRequest 객체에 담아서 제공

### HTTP 요청 데이터
* GET
** body 데이터 없이 query parameter로만 데이터 전송
** 페이지 요청, 검색, 필터 기능에 사용
** 데이터 전송의 한계가 명확함

* POST
** 기본 타입은 content-type 헤더에 application/x-www-form.urlencorded 가 들어감
** query parameter 로 전달 가능하지만, body도 존재
** 주로 데이터를 보내야 하니, 회원 가입, 주문, 게시 등등에 사용됨
** 이후 나올 내용으로 컨트롤러에 RestController를 사용하여 viewResolver를 사용하지 않는다면 body 데이터만 전송하여 REST API를 만들때 사용할 JSON 형식으로 데이터를 주고 받는 경우가 많음

TIP: JSON 형식 -> {"datafieldname1": dataValue1, "datafieldname2": dataValue2, "datafieldname3": dataValue3}


### query Parameter 실습

#### 요구사항: id, username, age를 가진 데이터를 /request-json으로 받을 수 있게 해주세요

* url-mapping: /request-param
* param: id, username, age
* HelloData
** id -> Long, NonNull
** username -> String, NotEmpty
** age -> int, Range(19~100)
* url-mapping: /request-json

[source,java]
----
/**
 * JSON 형식 전송
 *
 * content-type -> json
 * message body: {"id": 1, "username":"hello", "age":20}
 */
@WebServlet(name="requestBodyJsonServlet", urlPatterns = "/request-json")
public class RequestBodyJsonServlet extends HttpServlet {
    ObjectMapper objectMapper = new ObjectMapper();
    // objectmapper를 이용해 json 형식으로 전달받은 body data를 특정 객체로 변환
    @Override
    protected void service(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        ServletInputStream inputStream = request.getInputStream();
        String messageBody = StreamUtils.copyToString(inputStream, StandardCharsets.UTF_8);

        HelloData data = objectMapper.readValue(messageBody, HelloData.class);
        System.out.println(data);
        response.getWriter().write(data.toString());
    }
}
----





















































































































































































































































































































































































































